export const wetonData = [
      // ===== SENIN (Neptu 4) =====
      {
        hari: "Senin",
        hariNeptu: 4,
        pasaran: "Legi",
        pasaranNeptu: 5,
        totalNeptu: 9,
        dewiLindung: "Dewi Sri",
        rakam: null,
        karakterUtama: "Lembut dan penyayang, cocok jadi pemimpin keluarga",
        sifatPositif: [
          "Penyayang",
          "Lembut",
          "Sabar",
          "Bijaksana",
          "Setia",
          "Pekerja keras",
        ],
        sifatNegatif: ["Terlalu lembek", "Susah tegas", "Gampang dimanfaatkan"],
        pekerjaanCocok: ["Guru", "Perawat", "Konselor", "HR", "Social Worker"],
        rezekiKarir:
          "Rezeki datang dari kebaikan hati. Cocok kerja yang berhubungan dengan orang banyak.",
        cintaJodoh:
          "Sangat setia dan penyayang. Butuh pasangan yang menghargai kelembutan.",
        jodohCocok: ["Rabu Kliwon", "Kamis Pahing", "Jumat Wage"],
        tipsDo: ["Manfaatkan kelembutan", "Tetap konsisten", "Bantu sesama"],
        tipsDont: [
          "Jangan terlalu lembek",
          "Jangan gampang dimanfaatkan",
          "Jangan ragu ambil keputusan",
        ],
        kataKunci: "Si Lembut yang Penyayang",
      },
      {
        hari: "Senin",
        hariNeptu: 4,
        pasaran: "Pahing",
        pasaranNeptu: 9,
        totalNeptu: 13,
        dewiLindung: "Batara Surya",
        rakam: null,
        karakterUtama: "Berani dan tegas, jiwa kepemimpinan kuat",
        sifatPositif: [
          "Berani",
          "Tegas",
          "Jujur",
          "Pemimpin natural",
          "Pantang menyerah",
        ],
        sifatNegatif: [
          "Keras kepala",
          "Galak",
          "Kadang arogan",
          "Kurang sabar",
        ],
        pekerjaanCocok: [
          "Pemimpin",
          "Militer",
          "Polisi",
          "Pengusaha",
          "Manajer",
        ],
        rezekiKarir:
          "Rezeki datang dari keberanian mengambil risiko. Puncak karir di usia 35-50 tahun.",
        cintaJodoh:
          "Protektif dan dominan. Butuh pasangan yang bisa mengimbangi ketegasan.",
        jodohCocok: ["Rabu Legi", "Kamis Pon", "Sabtu Wage"],
        tipsDo: [
          "Manfaatkan keberanian",
          "Jadi pemimpin",
          "Ambil tanggung jawab",
        ],
        tipsDont: [
          "Jangan terlalu keras",
          "Jangan arogan",
          "Jangan mengintimidasi",
        ],
        kataKunci: "Si Pemberani yang Tegas",
      },
      {
        hari: "Senin",
        hariNeptu: 4,
        pasaran: "Pon",
        pasaranNeptu: 7,
        totalNeptu: 11,
        dewiLindung: "Dewi Saraswati",
        rakam: null,
        karakterUtama: "Cerdas dan kreatif, pandai bergaul",
        sifatPositif: [
          "Cerdas",
          "Kreatif",
          "Komunikatif",
          "Artistik",
          "Inovatif",
        ],
        sifatNegatif: ["Perfeksionis", "Overthinking", "Gampang bosan"],
        pekerjaanCocok: [
          "Desainer",
          "Seniman",
          "Penulis",
          "Marketing",
          "Content Creator",
        ],
        rezekiKarir:
          "Rezeki datang dari kreativitas. Harus berani eksplorasi dan networking.",
        cintaJodoh:
          "Romantis dan ekspresif. Butuh pasangan yang menghargai seni.",
        jodohCocok: ["Rabu Pahing", "Kamis Wage", "Jumat Legi"],
        tipsDo: [
          "Eksplorasi kreativitas",
          "Networking aktif",
          "Berani coba hal baru",
        ],
        tipsDont: [
          "Jangan terlalu perfeksionis",
          "Jangan overthink",
          "Jangan gampang bosan",
        ],
        kataKunci: "Si Kreatif yang Inovatif",
      },
      {
        hari: "Senin",
        hariNeptu: 4,
        pasaran: "Wage",
        pasaranNeptu: 4,
        totalNeptu: 8,
        dewiLindung: null,
        rakam: "Air mengalir (rezeki lancar tapi harus dijaga)",
        karakterUtama: "Tenang dan stabil, hemat dan bijaksana",
        sifatPositif: ["Tenang", "Stabil", "Hemat", "Bijaksana", "Konsisten"],
        sifatNegatif: ["Pelit", "Terlalu hati-hati", "Kurang berani"],
        pekerjaanCocok: ["Akuntan", "Keuangan", "Auditor", "Pegawai Bank"],
        rezekiKarir:
          "Rezeki datang dari kehati-hatian mengelola uang. Cocok di bidang finansial.",
        cintaJodoh: "Setia tapi pelit. Butuh pasangan yang paham soal hemat.",
        jodohCocok: ["Rabu Kliwon", "Kamis Legi", "Sabtu Pahing"],
        tipsDo: ["Kelola keuangan dengan baik", "Tetap hemat", "Konsisten"],
        tipsDont: [
          "Jangan terlalu pelit",
          "Jangan terlalu takut",
          "Jangan perhitungan berlebihan",
        ],
        kataKunci: "Si Hemat yang Bijaksana",
      },
      {
        hari: "Senin",
        hariNeptu: 4,
        pasaran: "Kliwon",
        pasaranNeptu: 8,
        totalNeptu: 12,
        dewiLindung: "Batara Kala",
        rakam: null,
        karakterUtama: "Mistis dan intuitif, spiritual kuat",
        sifatPositif: [
          "Intuitif kuat",
          "Spiritual",
          "Peka",
          "Bijaksana",
          "Kalem",
        ],
        sifatNegatif: ["Terlalu serius", "Pendiam", "Susah bergaul"],
        pekerjaanCocok: [
          "Rohaniwan",
          "Healer",
          "Konselor Spiritual",
          "Peneliti",
        ],
        rezekiKarir:
          "Rezeki datang dari jalan spiritual. Harus rajin ibadah dan berbagi.",
        cintaJodoh:
          "Setia dan mendalam. Butuh pasangan yang paham dunia spiritual.",
        jodohCocok: ["Rabu Wage", "Kamis Kliwon", "Jumat Pon"],
        tipsDo: [
          "Manfaatkan intuisi",
          "Rajin ibadah",
          "Berbagi ilmu spiritual",
        ],
        tipsDont: [
          "Jangan terlalu serius",
          "Jangan anti sosial",
          "Jangan sombong karena spiritual",
        ],
        kataKunci: "Si Spiritual yang Intuitif",
      },

      // ===== SELASA (Neptu 3) =====
      {
        hari: "Selasa",
        hariNeptu: 3,
        pasaran: "Legi",
        pasaranNeptu: 5,
        totalNeptu: 8,
        dewiLindung: "Dewi Lakshmi",
        rakam: null,
        karakterUtama: "Beruntung dalam rezeki, mudah dapat uang",
        sifatPositif: [
          "Beruntung",
          "Optimis",
          "Murah hati",
          "Mudah dapat rezeki",
        ],
        sifatNegatif: ["Boros", "Kurang menabung", "Gampang keluar uang"],
        pekerjaanCocok: ["Sales", "Entrepreneur", "Trader", "Investor"],
        rezekiKarir:
          "Rezeki datang mudah tapi juga mudah hilang. Harus rajin menabung.",
        cintaJodoh:
          "Murah hati dan romantis. Suka traktir, kadang kelewat boros.",
        jodohCocok: ["Kamis Wage", "Jumat Kliwon", "Minggu Pahing"],
        tipsDo: ["Kelola keuangan ketat", "Rajin menabung", "Investasi"],
        tipsDont: [
          "Jangan boros",
          "Jangan suka traktir berlebihan",
          "Jangan lupa tabung",
        ],
        kataKunci: "Si Beruntung yang Boros",
      },
      {
        hari: "Selasa",
        hariNeptu: 3,
        pasaran: "Pahing",
        pasaranNeptu: 9,
        totalNeptu: 12,
        dewiLindung: "Batara Brahma",
        rakam: null,
        karakterUtama: "Pemimpin visioner, berani bermimpi besar",
        sifatPositif: [
          "Visioner",
          "Berani",
          "Ambisius",
          "Inspiratif",
          "Charismatic",
        ],
        sifatNegatif: ["Terlalu ambisius", "Kurang realistis", "Suka ngayal"],
        pekerjaanCocok: [
          "CEO",
          "Founder",
          "Direktur",
          "Motivator",
          "Public Speaker",
        ],
        rezekiKarir:
          "Rezeki datang dari visi besar. Harus balance mimpi dengan eksekusi.",
        cintaJodoh:
          "Romantis dan idealis. Butuh pasangan yang support mimpi besar.",
        jodohCocok: ["Kamis Legi", "Jumat Wage", "Minggu Pon"],
        tipsDo: ["Kejar mimpi besar", "Eksekusi visi", "Inspirasi orang"],
        tipsDont: [
          "Jangan cuma ngayal",
          "Jangan lupa eksekusi",
          "Jangan arogan",
        ],
        kataKunci: "Si Visioner yang Ambisius",
      },
      {
        hari: "Selasa",
        hariNeptu: 3,
        pasaran: "Pon",
        pasaranNeptu: 7,
        totalNeptu: 10,
        dewiLindung: "Dewi Saraswati",
        rakam: null,
        karakterUtama: "Cerdas dan pandai, kreatif dan artistik",
        sifatPositif: [
          "Sangat cerdas",
          "Kreatif",
          "Komunikatif",
          "Penyabar",
          "Bijaksana",
          "Loyal",
          "Berwibawa",
        ],
        sifatNegatif: [
          "Terlalu perfeksionis",
          "Overthinking",
          "Kurang tegas",
          "Pendiam",
          "Sensitif",
          "Kurang percaya diri",
        ],
        pekerjaanCocok: [
          "Guru",
          "Dosen",
          "Peneliti",
          "Penulis",
          "Seniman",
          "Konsultan",
        ],
        rezekiKarir:
          "Rezeki datang dari kecerdasan dan kreativitas. Puncak karir di usia 35-50 tahun. Harus berani networking.",
        cintaJodoh:
          "Romantis tapi pemalu. Butuh pasangan yang bisa memahami sifat pendiam.",
        jodohCocok: [
          "Minggu Wage",
          "Rabu Kliwon",
          "Jumat Legi",
          "Kamis Pahing",
          "Sabtu Pon",
        ],
        tipsDo: [
          "Manfaatkan kecerdasan",
          "Ekspresikan kreativitas",
          "Berani ambil keputusan",
          "Networking aktif",
          "Percaya diri",
        ],
        tipsDont: [
          "Jangan terlalu perfeksionis",
          "Jangan terlalu pendiam",
          "Jangan overthinking",
          "Jangan rendah diri",
        ],
        kataKunci: "Si Bijak yang Kreatif",
      },
      {
        hari: "Selasa",
        hariNeptu: 3,
        pasaran: "Wage",
        pasaranNeptu: 4,
        totalNeptu: 7,
        dewiLindung: null,
        rakam: "Tanah subur (rezeki dari kerja keras)",
        karakterUtama: "Pekerja keras dan ulet, tekun dan sabar",
        sifatPositif: ["Pekerja keras", "Ulet", "Tekun", "Sabar", "Konsisten"],
        sifatNegatif: ["Terlalu serius", "Workaholic", "Kurang santai"],
        pekerjaanCocok: ["Petani", "Buruh", "Tukang", "Operator", "Teknisi"],
        rezekiKarir:
          "Rezeki datang dari kerja keras tanpa henti. Puncak karir lambat tapi pasti.",
        cintaJodoh:
          "Setia dan pekerja keras. Butuh pasangan yang paham sifat workaholic.",
        jodohCocok: ["Kamis Kliwon", "Jumat Pahing", "Minggu Legi"],
        tipsDo: ["Kerja keras konsisten", "Tetap sabar", "Terus belajar"],
        tipsDont: [
          "Jangan terlalu workaholic",
          "Jangan lupa istirahat",
          "Jangan stress",
        ],
        kataKunci: "Si Pekerja Keras yang Ulet",
      },
      {
        hari: "Selasa",
        hariNeptu: 3,
        pasaran: "Kliwon",
        pasaranNeptu: 8,
        totalNeptu: 11,
        dewiLindung: "Batara Wisnu",
        rakam: null,
        karakterUtama: "Intuitif kuat dan bertanggung jawab",
        sifatPositif: [
          "Intuitif kuat",
          "Bertanggung jawab",
          "Pekerja keras",
          "Setia",
          "Bisa dipercaya",
          "Konsisten",
          "Stabil",
        ],
        sifatNegatif: [
          "Kurang ekspresif",
          "Overthinking",
          "Susah mengungkapkan perasaan",
        ],
        pekerjaanCocok: ["Pemimpin", "Pengusaha", "Manajer", "Konsultan"],
        rezekiKarir:
          "Rezeki datang dari kerja keras yang konsisten. Cocok jadi pemimpin atau pengusaha. Harus rajin menabung.",
        cintaJodoh:
          "Setia dan protektif. Butuh pasangan yang bisa memahami sifat pendiam.",
        jodohCocok: ["Minggu Wage", "Rabu Kliwon", "Jumat Legi"],
        tipsDo: [
          "Manfaatkan intuisi",
          "Konsisten bekerja",
          "Jaga kesetiaan",
          "Rajin menabung",
        ],
        tipsDont: [
          "Jangan terlalu pendiam",
          "Jangan overthinking",
          "Jangan keras kepala",
        ],
        kataKunci: "Si Intuitif yang Bertanggung Jawab",
      },

      // ===== RABU (Neptu 7) =====
      {
        hari: "Rabu",
        hariNeptu: 7,
        pasaran: "Legi",
        pasaranNeptu: 5,
        totalNeptu: 12,
        dewiLindung: "Dewi Ratih",
        rakam: null,
        karakterUtama: "Cantik/tampan, menarik perhatian, karismatik",
        sifatPositif: [
          "Menarik",
          "Karismatik",
          "Komunikatif",
          "Percaya diri",
          "Populer",
        ],
        sifatNegatif: ["Gengsi tinggi", "Sombong", "Boros untuk penampilan"],
        pekerjaanCocok: ["Model", "Artis", "Influencer", "MC", "Public Figure"],
        rezekiKarir:
          "Rezeki datang dari penampilan dan karisma. Harus jaga image tapi jangan boros.",
        cintaJodoh:
          "Banyak yang suka karena menarik. Harus pilih dengan bijak.",
        jodohCocok: ["Jumat Kliwon", "Sabtu Wage", "Minggu Pahing"],
        tipsDo: ["Manfaatkan karisma", "Jaga penampilan", "Network luas"],
        tipsDont: [
          "Jangan sombong",
          "Jangan boros penampilan",
          "Jangan pilih-pilih berlebihan",
        ],
        kataKunci: "Si Menarik yang Karismatik",
      },
      {
        hari: "Rabu",
        hariNeptu: 7,
        pasaran: "Pahing",
        pasaranNeptu: 9,
        totalNeptu: 16,
        dewiLindung: "Batara Indra",
        rakam: null,
        karakterUtama: "Kuat dan tangguh, fighter sejati",
        sifatPositif: [
          "Kuat",
          "Tangguh",
          "Pantang menyerah",
          "Pemberani",
          "Pelindung",
        ],
        sifatNegatif: ["Keras kepala", "Galak", "Sulit dikritik"],
        pekerjaanCocok: [
          "Atlet",
          "Bodyguard",
          "Security",
          "TNI/Polri",
          "Pelatih",
        ],
        rezekiKarir:
          "Rezeki datang dari kekuatan fisik/mental. Harus jaga kesehatan dan stamina.",
        cintaJodoh: "Protektif berlebihan. Butuh pasangan yang kuat mental.",
        jodohCocok: ["Jumat Pon", "Sabtu Legi", "Senin Wage"],
        tipsDo: ["Jaga stamina", "Lindungi keluarga", "Latihan konsisten"],
        tipsDont: [
          "Jangan terlalu galak",
          "Jangan keras kepala",
          "Jangan intimidasi",
        ],
        kataKunci: "Si Fighter yang Tangguh",
      },
      {
        hari: "Rabu",
        hariNeptu: 7,
        pasaran: "Pon",
        pasaranNeptu: 7,
        totalNeptu: 14,
        dewiLindung: "Dewi Saraswati",
        rakam: null,
        karakterUtama: "Sangat cerdas dan bijaksana, teacher natural",
        sifatPositif: [
          "Sangat cerdas",
          "Bijaksana",
          "Sabar mengajar",
          "Komunikatif",
          "Inspiratif",
        ],
        sifatNegatif: [
          "Perfeksionis mengajar",
          "Terlalu idealis",
          "Kadang menggurui",
        ],
        pekerjaanCocok: [
          "Guru besar",
          "Profesor",
          "Mentor",
          "Coach",
          "Trainer",
        ],
        rezekiKarir:
          "Rezeki datang dari mengajar dan membimbing. Semakin senior semakin dihargai.",
        cintaJodoh: "Suka ngajarin pasangan. Butuh pasangan yang mau belajar.",
        jodohCocok: ["Jumat Wage", "Sabtu Kliwon", "Senin Legi"],
        tipsDo: ["Terus mengajar", "Berbagi ilmu", "Jadi mentor"],
        tipsDont: [
          "Jangan menggurui",
          "Jangan terlalu idealis",
          "Jangan sombong ilmu",
        ],
        kataKunci: "Si Guru Besar yang Bijaksana",
      },
      {
        hari: "Rabu",
        hariNeptu: 7,
        pasaran: "Wage",
        pasaranNeptu: 4,
        totalNeptu: 13,
        dewiLindung: null,
        rakam: "Sumur Sinamba (jiwa erat dengan pengajaran)",
        karakterUtama: "Baik hati dan ramah, bijaksana, cocok jadi pengajar",
        sifatPositif: [
          "Baik hati",
          "Ramah",
          "Mudah bergaul",
          "Bijaksana",
          "Jujur",
          "Hemat/irit",
          "Menghargai uang",
          "Pembelajar baik",
        ],
        sifatNegatif: [
          "Kadang bicara keras",
          "Terlalu hati-hati",
          "Pelit",
          "Sulit mandiri",
          "Kurang percaya diri untuk usaha sendiri",
        ],
        pekerjaanCocok: [
          "Guru",
          "Dosen",
          "Pelatih",
          "Instruktur",
          "Tutor",
          "Pegawai/karyawan",
        ],
        rezekiKarir:
          "Sangat cocok jadi pengajar. Tidak cocok jadi pengusaha mandiri, lebih nyaman kerja untuk orang lain. Rezeki dari mengajar dan membimbing. Neptu 11 adalah yang terkecil, membawa pelajaran kesederhanaan sejak kecil.",
        cintaJodoh:
          "Setia dan jujur. Kadang terlalu hati-hati soal uang. Butuh pasangan yang bisa melengkapi terutama soal finansial.",
        jodohCocok: [
          "Kamis Legi",
          "Sabtu Wage",
          "Selasa Legi",
          "Minggu Kliwon",
          "Jumat Pon",
          "Sabtu Pahing",
        ],
        tipsDo: [
          "Manfaatkan bakat mengajar",
          "Kerja untuk orang lain",
          "Tetap hemat",
          "Berbagi ilmu",
          "Terus belajar",
        ],
        tipsDont: [
          "Jangan terlalu pelit",
          "Jangan bicara terlalu keras",
          "Jangan maksain jadi pengusaha",
          "Jangan terlalu perhitungan",
          "Jangan rendah diri",
        ],
        kataKunci: "Si Guru yang Hemat",
      },
      {
        hari: "Rabu",
        hariNeptu: 7,
        pasaran: "Kliwon",
        pasaranNeptu: 8,
        totalNeptu: 15,
        dewiLindung: "Batara Kala",
        rakam: null,
        karakterUtama: "Mistis kuat, bisa melihat yang gaib",
        sifatPositif: [
          "Spiritual tinggi",
          "Intuitif kuat",
          "Bisa lihat hal gaib",
          "Bijaksana",
          "Pelindung",
        ],
        sifatNegatif: ["Terlalu serius", "Anti sosial", "Kadang menyeramkan"],
        pekerjaanCocok: [
          "Paranormal",
          "Spiritual healer",
          "Kiai/Ustadz",
          "Peneliti gaib",
        ],
        rezekiKarir:
          "Rezeki datang dari jalan spiritual. Harus gunakan kemampuan untuk kebaikan.",
        cintaJodoh:
          "Serius dan dalam. Butuh pasangan yang paham dunia spiritual.",
        jodohCocok: ["Jumat Legi", "Sabtu Pahing", "Senin Kliwon"],
        tipsDo: [
          "Gunakan kemampuan untuk baik",
          "Rajin ibadah",
          "Lindungi orang",
        ],
        tipsDont: [
          "Jangan pamer kemampuan",
          "Jangan menyeramkan",
          "Jangan anti sosial",
        ],
        kataKunci: "Si Spiritual yang Mistis",
      },

      // ===== KAMIS (Neptu 8) =====
      {
        hari: "Kamis",
        hariNeptu: 8,
        pasaran: "Legi",
        pasaranNeptu: 5,
        totalNeptu: 13,
        dewiLindung: "Dewi Parvati",
        rakam: null,
        karakterUtama: "Harmonis dan seimbang, bijaksana dalam keputusan",
        sifatPositif: [
          "Seimbang",
          "Harmonis",
          "Bijaksana",
          "Diplomatis",
          "Fair",
        ],
        sifatNegatif: [
          "Terlalu diplomatis",
          "Susah tegas",
          "Lamban ambil keputusan",
        ],
        pekerjaanCocok: [
          "Mediator",
          "Diplomat",
          "Hakim",
          "Konsultan",
          "Negosiator",
        ],
        rezekiKarir:
          "Rezeki datang dari kemampuan mediasi. Cocok jadi penengah konflik.",
        cintaJodoh:
          "Harmonis dan romantis. Butuh pasangan yang menghargai keseimbangan.",
        jodohCocok: ["Sabtu Wage", "Minggu Pahing", "Senin Pon"],
        tipsDo: ["Jadi mediator", "Jaga keseimbangan", "Diplomatis"],
        tipsDont: [
          "Jangan terlalu lamban",
          "Jangan takut tegas",
          "Jangan people pleaser",
        ],
        kataKunci: "Si Mediator yang Harmonis",
      },
      {
        hari: "Kamis",
        hariNeptu: 8,
        pasaran: "Pahing",
        pasaranNeptu: 9,
        totalNeptu: 17,
        dewiLindung: "Batara Agni",
        rakam: null,
        karakterUtama: "Berapi-api dan passionate, energi tinggi",
        sifatPositif: [
          "Passionate",
          "Energik",
          "Antusias",
          "Inspiratif",
          "Motivatif",
        ],
        sifatNegatif: ["Terlalu semangat", "Burnout mudah", "Impulsif"],
        pekerjaanCocok: [
          "Motivator",
          "Coach",
          "Trainer",
          "Entertainer",
          "Aktivis",
        ],
        rezekiKarir:
          "Rezeki datang dari semangat menginspirasi. Harus jaga stamina dan istirahat.",
        cintaJodoh:
          "Passionate dan romantic. Butuh pasangan yang bisa ikuti energi.",
        jodohCocok: ["Sabtu Legi", "Minggu Pon", "Selasa Wage"],
        tipsDo: [
          "Gunakan energi untuk inspirasi",
          "Motivasi orang",
          "Tetap semangat",
        ],
        tipsDont: [
          "Jangan burnout",
          "Jangan terlalu impulsif",
          "Jangan lupa istirahat",
        ],
        kataKunci: "Si Passionate yang Energik",
      },
      {
        hari: "Kamis",
        hariNeptu: 8,
        pasaran: "Pon",
        pasaranNeptu: 7,
        totalNeptu: 15,
        dewiLindung: "Dewi Saraswati",
        rakam: null,
        karakterUtama: "Cerdas dan kreatif, inovator handal",
        sifatPositif: [
          "Sangat cerdas",
          "Inovatif",
          "Kreatif",
          "Problem solver",
          "Visioner",
        ],
        sifatNegatif: ["Perfeksionis", "Overthinking", "Susah puas"],
        pekerjaanCocok: [
          "Scientist",
          "Researcher",
          "Inventor",
          "Tech Innovator",
          "Designer",
        ],
        rezekiKarir:
          "Rezeki datang dari inovasi. Harus berani eksekusi ide-ide cemerlang.",
        cintaJodoh: "Cerdas dan idealis. Butuh pasangan yang intelek.",
        jodohCocok: ["Sabtu Kliwon", "Minggu Wage", "Selasa Legi"],
        tipsDo: ["Eksekusi ide", "Terus inovasi", "Kolaborasi"],
        tipsDont: [
          "Jangan perfeksionis berlebihan",
          "Jangan overthink",
          "Jangan kerja sendiri terus",
        ],
        kataKunci: "Si Inovator yang Cerdas",
      },
      {
        hari: "Kamis",
        hariNeptu: 8,
        pasaran: "Wage",
        pasaranNeptu: 4,
        totalNeptu: 12,
        dewiLindung: null,
        rakam: "Batu karang (kuat dan kokoh)",
        karakterUtama: "Kokoh dan stabil, bisa diandalkan",
        sifatPositif: [
          "Stabil",
          "Kokoh",
          "Reliable",
          "Bertanggung jawab",
          "Konsisten",
        ],
        sifatNegatif: ["Kaku", "Susah adaptasi", "Konservatif"],
        pekerjaanCocok: [
          "Arsitek",
          "Engineer",
          "Project Manager",
          "Supervisor",
        ],
        rezekiKarir:
          "Rezeki datang dari konsistensi. Cocok di bidang yang butuh ketelitian.",
        cintaJodoh:
          "Stabil dan setia. Butuh pasangan yang menghargai kestabilan.",
        jodohCocok: ["Sabtu Pahing", "Minggu Legi", "Selasa Kliwon"],
        tipsDo: ["Jaga konsistensi", "Tetap reliable", "Teliti"],
        tipsDont: [
          "Jangan terlalu kaku",
          "Jangan anti perubahan",
          "Jangan boring",
        ],
        kataKunci: "Si Kokoh yang Stabil",
      },
      {
        hari: "Kamis",
        hariNeptu: 8,
        pasaran: "Kliwon",
        pasaranNeptu: 8,
        totalNeptu: 16,
        dewiLindung: "Dewa Basuki",
        rakam: null,
        karakterUtama: "Cerdas dan tajam, intuitif kuat, bertanggung jawab",
        sifatPositif: [
          "Cerdas dan tajam",
          "Intuitif kuat",
          "Pandai menyimpan rahasia",
          "Bertanggung jawab",
          "Pekerja keras",
          "Stabil",
          "Konsisten",
          "Setia",
          "Protektif",
          "Dewasa",
        ],
        sifatNegatif: [
          "Keras kepala",
          "Terlalu serius",
          "Sulit mengekspresikan perasaan",
          "Overthinking",
        ],
        pekerjaanCocok: [
          "Pemimpin",
          "Pengusaha",
          "Manajer",
          "Eksekutif",
          "Direktur",
        ],
        rezekiKarir:
          "Rezeki datang dari kerja keras yang konsisten. Cocok jadi pemimpin atau pengusaha. Harus rajin menabung karena cenderung boros kalau tidak dikontrol.",
        cintaJodoh:
          "Sangat setia dan protektif ke keluarga. Butuh pasangan yang bisa memahami sifat serius.",
        jodohCocok: ["Minggu Legi", "Selasa Pahing", "Rabu Wage", "Jumat Wage"],
        tipsDo: [
          "Manfaatkan intuisi",
          "Konsisten bekerja",
          "Jaga kesetiaan",
          "Rajin menabung",
          "Jadi penopang keluarga",
        ],
        tipsDont: [
          "Jangan terlalu keras kepala",
          "Jangan terlalu serius",
          "Jangan pendam perasaan",
          "Jangan overthinking",
        ],
        kataKunci: "Si Pemimpin yang Stabil",
      },

      // ===== JUMAT (Neptu 6) =====
      {
        hari: "Jumat",
        hariNeptu: 6,
        pasaran: "Legi",
        pasaranNeptu: 5,
        totalNeptu: 11,
        dewiLindung: "Dewi Fortuna",
        rakam: null,
        karakterUtama: "Beruntung dan disukai banyak orang",
        sifatPositif: [
          "Beruntung",
          "Disukai",
          "Ramah",
          "Murah hati",
          "Populer",
        ],
        sifatNegatif: ["Boros", "Gampang percaya", "Kurang selektif"],
        pekerjaanCocok: ["Sales", "Marketing", "Customer Service", "PR"],
        rezekiKarir:
          "Rezeki datang mudah dari network. Harus kelola keuangan dengan baik.",
        cintaJodoh:
          "Banyak yang suka. Harus pilih dengan bijak dan jangan gampang percaya.",
        jodohCocok: ["Minggu Kliwon", "Selasa Pahing", "Rabu Wage"],
        tipsDo: ["Manfaatkan network", "Jaga hubungan baik", "Kelola keuangan"],
        tipsDont: [
          "Jangan boros",
          "Jangan gampang percaya",
          "Jangan pilih asal",
        ],
        kataKunci: "Si Beruntung yang Populer",
      },
      {
        hari: "Jumat",
        hariNeptu: 6,
        pasaran: "Pahing",
        pasaranNeptu: 9,
        totalNeptu: 15,
        dewiLindung: "Batara Brahma",
        rakam: null,
        karakterUtama: "Kreatif dan visioner, pemikir besar",
        sifatPositif: [
          "Visioner",
          "Kreatif",
          "Out of the box",
          "Inspiratif",
          "Berani",
        ],
        sifatNegatif: ["Terlalu idealis", "Kurang praktis", "Suka ngayal"],
        pekerjaanCocok: [
          "Creative Director",
          "Architect",
          "Designer",
          "Artist",
        ],
        rezekiKarir:
          "Rezeki datang dari ide kreatif. Harus balance visi dengan eksekusi.",
        cintaJodoh:
          "Idealis dalam cinta. Butuh pasangan yang support kreativitas.",
        jodohCocok: ["Minggu Pon", "Selasa Wage", "Rabu Legi"],
        tipsDo: ["Kejar visi kreatif", "Eksekusi ide", "Kolaborasi"],
        tipsDont: [
          "Jangan cuma ngayal",
          "Jangan terlalu idealis",
          "Jangan lupa praktis",
        ],
        kataKunci: "Si Visioner yang Kreatif",
      },
      {
        hari: "Jumat",
        hariNeptu: 6,
        pasaran: "Pon",
        pasaranNeptu: 7,
        totalNeptu: 13,
        dewiLindung: "Batara Indra",
        rakam: null,
        karakterUtama: "Pandai bergaul, kreatif, karismatik",
        sifatPositif: [
          "Komunikatif",
          "Cerdas",
          "Optimis",
          "Loyal",
          "Romantis",
          "Beruntung dalam cinta",
          "Pandai bergaul",
          "Punya karisma",
        ],
        sifatNegatif: [
          "Ambisius berlebihan",
          "Suka disanjung",
          "Gengsi tinggi",
          "Kadang sombong",
          "Boros",
          "Kurang sabar",
        ],
        pekerjaanCocok: [
          "Public figure",
          "Sales",
          "Marketing",
          "Entertainer",
          "MC",
          "Presenter",
        ],
        rezekiKarir:
          "Rezeki datang dari networking dan komunikasi. Puncak karir di usia 30-45 tahun. Harus kelola keuangan dengan disiplin.",
        cintaJodoh:
          "Beruntung dalam percintaan, banyak yang suka. Harus pilih dengan bijak.",
        jodohCocok: [
          "Minggu Kliwon",
          "Selasa Legi",
          "Rabu Pahing",
          "Sabtu Wage",
        ],
        tipsDo: [
          "Manfaatkan skill komunikasi",
          "Kelola keuangan dengan disiplin",
          "Tetap rendah hati",
          "Jaga keseimbangan ambisi",
        ],
        tipsDont: [
          "Jangan terlalu gengsi",
          "Jangan boros untuk pamer",
          "Jangan lupa orang yang bantu",
          "Jangan lupain keluarga",
        ],
        kataKunci: "Si Populer yang Ambisius",
      },
      {
        hari: "Jumat",
        hariNeptu: 6,
        pasaran: "Wage",
        pasaranNeptu: 4,
        totalNeptu: 10,
        dewiLindung: null,
        rakam: "Pohon bambu (lentur tapi kuat)",
        karakterUtama: "Fleksibel dan adaptif, bisa menyesuaikan diri",
        sifatPositif: [
          "Fleksibel",
          "Adaptif",
          "Easy going",
          "Humble",
          "Kooperatif",
        ],
        sifatNegatif: [
          "Kurang tegas",
          "Gampang dipengaruhi",
          "Pendirian lemah",
        ],
        pekerjaanCocok: ["Freelancer", "Consultant", "Coordinator", "Admin"],
        rezekiKarir:
          "Rezeki datang dari kemampuan adaptasi. Cocok kerja di berbagai bidang.",
        cintaJodoh: "Fleksibel dan pengertian. Kadang terlalu mengalah.",
        jodohCocok: ["Minggu Pahing", "Selasa Kliwon", "Rabu Wage"],
        tipsDo: ["Manfaatkan fleksibilitas", "Adaptasi cepat", "Kooperatif"],
        tipsDont: [
          "Jangan terlalu mengalah",
          "Jangan lemah pendirian",
          "Jangan gampang dipengaruhi",
        ],
        kataKunci: "Si Fleksibel yang Adaptif",
      },
      {
        hari: "Jumat",
        hariNeptu: 6,
        pasaran: "Kliwon",
        pasaranNeptu: 8,
        totalNeptu: 14,
        dewiLindung: "Batara Kala",
        rakam: null,
        karakterUtama: "Spiritual dan intuitif, peka terhadap energi",
        sifatPositif: [
          "Spiritual",
          "Intuitif",
          "Peka energi",
          "Bijaksana",
          "Kalem",
        ],
        sifatNegatif: [
          "Overthinking spiritual",
          "Terlalu serius",
          "Anti sosial",
        ],
        pekerjaanCocok: ["Spiritual Coach", "Healer", "Therapist", "Counselor"],
        rezekiKarir:
          "Rezeki datang dari jalan spiritual. Harus gunakan kemampuan untuk membantu.",
        cintaJodoh:
          "Spiritual dan dalam. Butuh pasangan yang paham dunia batin.",
        jodohCocok: ["Minggu Wage", "Selasa Pon", "Rabu Kliwon"],
        tipsDo: [
          "Manfaatkan intuisi",
          "Rajin ibadah",
          "Berbagi energi positif",
        ],
        tipsDont: [
          "Jangan overthink spiritual",
          "Jangan anti sosial",
          "Jangan sombong spiritual",
        ],
        kataKunci: "Si Spiritual yang Peka",
      },

      // ===== SABTU (Neptu 9) =====
      {
        hari: "Sabtu",
        hariNeptu: 9,
        pasaran: "Legi",
        pasaranNeptu: 5,
        totalNeptu: 14,
        dewiLindung: "Dewi Kali",
        rakam: null,
        karakterUtama: "Kuat dan mandiri, fighter sejati",
        sifatPositif: [
          "Kuat",
          "Mandiri",
          "Pemberani",
          "Pantang menyerah",
          "Leader",
        ],
        sifatNegatif: ["Keras kepala", "Galak", "Susah dikritik"],
        pekerjaanCocok: ["Entrepreneur", "CEO", "Leader", "Founder"],
        rezekiKarir: "Rezeki datang dari kemandirian. Cocok jadi bos sendiri.",
        cintaJodoh: "Dominan dan protektif. Butuh pasangan yang kuat mental.",
        jodohCocok: ["Senin Kliwon", "Rabu Pahing", "Kamis Wage"],
        tipsDo: [
          "Manfaatkan kemandirian",
          "Jadi leader",
          "Berani ambil risiko",
        ],
        tipsDont: [
          "Jangan terlalu keras",
          "Jangan anti kritik",
          "Jangan dominan berlebihan",
        ],
        kataKunci: "Si Mandiri yang Kuat",
      },
      {
        hari: "Sabtu",
        hariNeptu: 9,
        pasaran: "Pahing",
        pasaranNeptu: 9,
        totalNeptu: 18,
        dewiLindung: "Dewi Durga",
        rakam: null,
        karakterUtama: "Panas membara, blak-blakan, nekat dan berani",
        sifatPositif: [
          "Cerdas dan tajam",
          "Pemberani",
          "Jujur",
          "Cepat tenang setelah marah",
          "Sebenarnya penakut di balik keganasan",
        ],
        sifatNegatif: [
          "Galak dan tajam ucapannya",
          "Kurang pandai menyimpan uang",
          "Impulsif",
          "Boros",
          "Sulit mengelola keuangan",
          "Mudah tersinggung",
          "Emosi mudah tersulut",
        ],
        pekerjaanCocok: [
          "Pengusaha nekat",
          "Sales aggressive",
          "Entrepreneur",
          "Trader",
          "Investor berisiko tinggi",
        ],
        rezekiKarir:
          "Masa keemasan: usia 12, 24, 48, 102 tahun. Rezeki tidak datang sendiri, harus kerja keras + doa. Perlu selamatan dengan bubur sumsum untuk buka jalan rezeki.",
        cintaJodoh:
          "Galak tapi sebenarnya penakut. Butuh pasangan yang bisa menenangkan.",
        jodohCocok: [
          "Rabu Legi",
          "Kamis Pon",
          "Minggu Kliwon",
          "Selasa Wage",
          "Jumat Legi",
        ],
        tipsDo: [
          "Kontrol emosi",
          "Kelola keuangan dengan ketat",
          "Manfaatkan keberanian",
          "Doa dan selamatan",
        ],
        tipsDont: [
          "Jangan impulsif belanja",
          "Jangan terlalu blak-blakan",
          "Jangan boros",
          "Jangan mudah tersinggung",
        ],
        kataKunci: "Si Api yang Berkobar",
      },
      {
        hari: "Sabtu",
        hariNeptu: 9,
        pasaran: "Pon",
        pasaranNeptu: 7,
        totalNeptu: 16,
        dewiLindung: "Dewi Saraswati",
        rakam: null,
        karakterUtama: "Cerdas dan kritis, analitikal tinggi",
        sifatPositif: [
          "Sangat cerdas",
          "Kritis",
          "Analitikal",
          "Teliti",
          "Objektif",
        ],
        sifatNegatif: ["Terlalu kritis", "Perfeksionis", "Susah puas"],
        pekerjaanCocok: ["Analyst", "Researcher", "Auditor", "Quality Control"],
        rezekiKarir:
          "Rezeki datang dari ketelitian. Cocok di bidang yang butuh analisis.",
        cintaJodoh:
          "Kritis dan analitikal. Butuh pasangan yang sabar dikritik.",
        jodohCocok: ["Senin Wage", "Rabu Legi", "Kamis Kliwon"],
        tipsDo: ["Manfaatkan kemampuan analisis", "Tetap objektif", "Teliti"],
        tipsDont: [
          "Jangan terlalu kritis",
          "Jangan perfeksionis berlebihan",
          "Jangan menyakiti dengan kritik",
        ],
        kataKunci: "Si Analis yang Kritis",
      },
      {
        hari: "Sabtu",
        hariNeptu: 9,
        pasaran: "Wage",
        pasaranNeptu: 4,
        totalNeptu: 13,
        dewiLindung: null,
        rakam: "Logam besi (keras dan kuat)",
        karakterUtama: "Keras dan tegas, disiplin tinggi",
        sifatPositif: [
          "Tegas",
          "Disiplin",
          "Konsisten",
          "Bertanggung jawab",
          "Reliable",
        ],
        sifatNegatif: ["Terlalu keras", "Kaku", "Kurang fleksibel"],
        pekerjaanCocok: ["Military", "Police", "Security", "Supervisor"],
        rezekiKarir:
          "Rezeki datang dari kedisiplinan. Cocok di bidang yang butuh ketegasan.",
        cintaJodoh:
          "Tegas dan protektif. Butuh pasangan yang bisa terima ketegasan.",
        jodohCocok: ["Senin Pahing", "Rabu Kliwon", "Kamis Legi"],
        tipsDo: ["Jaga kedisiplinan", "Tetap tegas", "Konsisten"],
        tipsDont: [
          "Jangan terlalu keras",
          "Jangan kaku berlebihan",
          "Jangan intimidasi",
        ],
        kataKunci: "Si Disiplin yang Tegas",
      },
      {
        hari: "Sabtu",
        hariNeptu: 9,
        pasaran: "Kliwon",
        pasaranNeptu: 8,
        totalNeptu: 17,
        dewiLindung: "Batara Yama",
        rakam: null,
        karakterUtama: "Mistis kuat dan menyeramkan, aura gelap",
        sifatPositif: [
          "Spiritual sangat tinggi",
          "Protektif",
          "Bijaksana",
          "Bisa tangkal kejahatan",
        ],
        sifatNegatif: ["Menyeramkan", "Anti sosial", "Terlalu serius"],
        pekerjaanCocok: [
          "Paranormal tingkat tinggi",
          "Kiai/Ustadz",
          "Spiritual protector",
        ],
        rezekiKarir:
          "Rezeki datang dari kemampuan spiritual tinggi. Harus gunakan untuk kebaikan.",
        cintaJodoh:
          "Menyeramkan tapi protektif. Butuh pasangan yang berani dan paham spiritual.",
        jodohCocok: ["Senin Legi", "Rabu Wage", "Kamis Pahing"],
        tipsDo: [
          "Gunakan kemampuan untuk lindungi",
          "Rajin ibadah",
          "Berbagi ilmu",
        ],
        tipsDont: [
          "Jangan menyeramkan berlebihan",
          "Jangan anti sosial",
          "Jangan pamer kemampuan",
        ],
        kataKunci: "Si Mistis yang Menyeramkan",
      },

      // ===== MINGGU (Neptu 5) =====
      {
        hari: "Minggu",
        hariNeptu: 5,
        pasaran: "Legi",
        pasaranNeptu: 5,
        totalNeptu: 10,
        dewiLindung: "Dewi Ratih",
        rakam: null,
        karakterUtama: "Cantik/tampan dan menarik, karisma natural",
        sifatPositif: [
          "Menarik",
          "Karismatik",
          "Ramah",
          "Populer",
          "Mudah disukai",
        ],
        sifatNegatif: ["Gengsi tinggi", "Boros penampilan", "Sombong"],
        pekerjaanCocok: [
          "Model",
          "Influencer",
          "Brand Ambassador",
          "Public Figure",
        ],
        rezekiKarir:
          "Rezeki datang dari penampilan. Harus jaga image tapi kelola keuangan.",
        cintaJodoh:
          "Banyak peminat. Harus pilih dengan bijak dan jangan sombong.",
        jodohCocok: ["Selasa Kliwon", "Rabu Pahing", "Kamis Wage"],
        tipsDo: ["Manfaatkan karisma", "Jaga penampilan", "Tetap humble"],
        tipsDont: [
          "Jangan sombong",
          "Jangan boros penampilan",
          "Jangan remehkan orang",
        ],
        kataKunci: "Si Menarik yang Karismatik",
      },
      {
        hari: "Minggu",
        hariNeptu: 5,
        pasaran: "Pahing",
        pasaranNeptu: 9,
        totalNeptu: 14,
        dewiLindung: "Batara Surya",
        rakam: null,
        karakterUtama: "Bercahaya dan inspiratif, leader natural",
        sifatPositif: [
          "Inspiratif",
          "Charismatic leader",
          "Optimis",
          "Energik",
          "Motivatif",
        ],
        sifatNegatif: [
          "Terlalu percaya diri",
          "Kadang arogan",
          "Suka jadi pusat perhatian",
        ],
        pekerjaanCocok: ["CEO", "Founder", "Motivator", "Public Speaker"],
        rezekiKarir:
          "Rezeki datang dari kepemimpinan. Semakin senior semakin bersinar.",
        cintaJodoh:
          "Charismatic dan romantic. Butuh pasangan yang support kepemimpinan.",
        jodohCocok: ["Selasa Wage", "Rabu Legi", "Kamis Kliwon"],
        tipsDo: ["Jadi leader inspiratif", "Motivasi orang", "Tetap humble"],
        tipsDont: [
          "Jangan arogan",
          "Jangan cari perhatian berlebihan",
          "Jangan lupa tim",
        ],
        kataKunci: "Si Pemimpin yang Bercahaya",
      },
      {
        hari: "Minggu",
        hariNeptu: 5,
        pasaran: "Pon",
        pasaranNeptu: 7,
        totalNeptu: 12,
        dewiLindung: "Dewi Saraswati",
        rakam: null,
        karakterUtama: "Cerdas dan bijaksana, teacher yang baik",
        sifatPositif: [
          "Cerdas",
          "Bijaksana",
          "Sabar",
          "Komunikatif",
          "Inspiratif",
        ],
        sifatNegatif: ["Perfeksionis", "Suka menggurui", "Terlalu idealis"],
        pekerjaanCocok: ["Professor", "Mentor", "Coach", "Trainer"],
        rezekiKarir:
          "Rezeki datang dari mengajar. Semakin tua semakin dihormati.",
        cintaJodoh: "Bijaksana dan sabar. Suka ngajarin pasangan.",
        jodohCocok: ["Selasa Pahing", "Rabu Kliwon", "Kamis Legi"],
        tipsDo: ["Terus mengajar", "Berbagi ilmu", "Jadi mentor"],
        tipsDont: [
          "Jangan menggurui",
          "Jangan terlalu idealis",
          "Jangan sombong ilmu",
        ],
        kataKunci: "Si Bijak yang Mengajar",
      },
      {
        hari: "Minggu",
        hariNeptu: 5,
        pasaran: "Wage",
        pasaranNeptu: 4,
        totalNeptu: 9,
        dewiLindung: null,
        rakam: "Embun pagi (segar dan bersih)",
        karakterUtama: "Segar dan positif, optimis tinggi",
        sifatPositif: [
          "Optimis",
          "Positif",
          "Cheerful",
          "Menyegarkan",
          "Mudah bergaul",
        ],
        sifatNegatif: ["Terlalu optimis", "Kurang realistis", "Kadang naif"],
        pekerjaanCocok: ["Entertainer", "MC", "Motivator", "Customer Service"],
        rezekiKarir:
          "Rezeki datang dari energi positif. Harus tetap realistis.",
        cintaJodoh:
          "Cheerful dan romantic. Butuh pasangan yang support optimisme.",
        jodohCocok: ["Selasa Legi", "Rabu Pon", "Kamis Pahing"],
        tipsDo: ["Sebarkan energi positif", "Tetap optimis", "Cheerful"],
        tipsDont: [
          "Jangan terlalu naif",
          "Jangan kurang realistis",
          "Jangan toxic positivity",
        ],
        kataKunci: "Si Optimis yang Ceria",
      },
      {
        hari: "Minggu",
        hariNeptu: 5,
        pasaran: "Kliwon",
        pasaranNeptu: 8,
        totalNeptu: 13,
        dewiLindung: "Batara Wisnu",
        rakam: null,
        karakterUtama: "Pelindung dan bertanggung jawab, protektif",
        sifatPositif: [
          "Protektif",
          "Bertanggung jawab",
          "Setia",
          "Reliable",
          "Kuat",
        ],
        sifatNegatif: ["Terlalu protektif", "Posesif", "Susah lepas kontrol"],
        pekerjaanCocok: ["Security Leader", "Bodyguard Manager", "Protector"],
        rezekiKarir:
          "Rezeki datang dari melindungi. Cocok jadi pelindung keluarga/organisasi.",
        cintaJodoh: "Sangat protektif dan setia. Kadang terlalu posesif.",
        jodohCocok: ["Selasa Kliwon", "Rabu Wage", "Kamis Pon"],
        tipsDo: ["Lindungi keluarga", "Tetap setia", "Jadi reliable"],
        tipsDont: [
          "Jangan terlalu posesif",
          "Jangan controlling",
          "Jangan overprotective",
        ],
        kataKunci: "Si Pelindung yang Setia",
      },
    ];
